export const photos = [
  "Calbee 1.jpg",
  "Calbee 2.jpg",
  "Calbee 3.jpg",
  "Calbee 4.jpg",
  "ITO EN 1-2.jpg",
  "ITO EN 1.jpg",
  "ITO EN 3.jpg",
  "ITO EN 4.jpg",
  "Oliana 1.jpg",
  "Oliana 2.jpg",
  "Oliana 3.jpg",
  "Oliana 4.jpg",
  "Orange 1.jpg",
  "Orange 2.jpg",
  "Orange 3.jpg",
  "Orange 4.jpg",
  "Sun Noodle 1.JPEG",
  "Sun Noodle 2.jpg",
  "Sun Noodle 3.jpg",
  "Sun Noodle 4.jpg",
  "UHA 1.jpg",
  "UHA 2.jpg",
  "UHA 3.jpg",
  "UHA 4.jpg"
];
